### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by vincentchalamon**
- [x] Fix Coding Style
- [x] Fix Code Sniffer
- [x] Fix Mess Detector
- [x] Fix PHPUnit

### CODE REVIEW

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon #179 has been merged. Please rebase and fix conflicts.

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest Rebased and fixed, it's RFR :-)

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon I get the following error message on `composer install`:

`Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In CheckDefinitionValidityPass.php line 49:
!!

!!    Please add the class to service "app.member_data_extractor.donations" even if it is constructed by a factory since
!!    we might need to add method calls based on compile-time checks.

!!

!!
!!
Script @auto-scripts was called via post-install-cmd`

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest This should be fixed now

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon So I can composer install now and run npm install without any unexpected problems.

But when I try to open localhost:8000 it shows that I do not have a homepage set.

"You're seeing this page because you haven't configured any homepage URL and debug mode is enabled."

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest Indeed, my bad! I've fixed it.
The Symfony 5.1 routing has evolved and I have upgraded the configuration in the Kernel.php file, but I've missed some points. It's fixed now.

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon So logging in works now. So I decided to try https://localhost:8080/mydata which fails with en exception.

`Argument 4 passed to App\Model\MemberModel::__construct() must implement interface Iterator, instance of Symfony\Component\DependencyInjection\Argument\RewindableGenerator given`

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest Does it work now?

Sorry for the ping-pong messages, we really need some functional tests!

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon I agree that we need functional test. But one problem at a time 👍 

I'm currently checking old code against new code (running them against the same database and comparing the results. Slow process.).

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest It's weird, on the original code, the MemberModel::prepareMemberData method has unaccessible code: https://github.com/BeWelcome/rox/blob/bootstrap4/src/Model/MemberModel.php#L602-L610

Could the unaccessible code be removed, or is it a mistake and the first return should be removed?

**Comment by vincentchalamon** [comment]
I've fixed the issues, but I'm stuck with the following error (maybe cause I don't have enough data on local).
Could you try locally with real data?

bewelcome

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon The dead code in the MemberExtractor can be removed.

The Member entity expects that an admin unit can be found for a member. As the seed data doesn't provide any for the created members the code through an exception.

That can be fixed for the test database by running this SQL:

insert into geonamesadminunits set    geonameid =2950157, 
    name=  'Land Berlin',
    fclass= 'A',
    fcode= 'ADM1',
    admin1 = 16,
    moddate = '2020-09-04',
    country = 'DE';
insert into geonamesadminunits set    
    geonameid = 1643012,
    name = 'Provinsi Papua',
    fclass = 'A',
    fcode = 'ADM1',
    country = 'IN',
    admin1 = '36',
    moddate = '2020-09-04';

This solve the issue for the data extractor till we hit the DoctrineFactory for the donations. (Using $this when not in object context.)

In general there are cities with out admin units set in the geonames data dump so a null as admin unit needs to be allowed but that is outside the scope of this pull request.

**Comment by vincentchalamon** [comment]
OK, this is working. I'm gonna push a fix about that.
Locally, I cannot get the zip download because of line https://github.com/BeWelcome/rox/blob/bootstrap4/src/Controller/MemberController.php#L137, I had to remove it. Do you remember why did you set it months ago?

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon I tried to get the page redirect to the profile in case an admin triggered the data export. But that doesn't really work. So I need to change that to the same behavior as the normal data export.

Other than that it works now, but I still want to see the compare so please be patient :)

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon No luck. First I ran into a max_execution timeout which was weird because that was set to 0 in the php.ini so I added set_ini call to set a deliberately high amount. Which work till it tried to extract the newsletters I ever created or translated.

The DoctrineExtractor has two problems: First it has too much donation in it's extraction method, second it assumes that the twig template only use the entity and no other information.

For the Newsletter the member would need to be given as a parameter (named creator). (That's the only one I assume.)

The generated zip files doesn't contain the gallery items.

**Comment by vincentchalamon** [comment]
> First I ran into a max_execution timeout which was weird because that was set to 0 in the php.ini so I added set_ini call to set a deliberately high amount.

The extractor code is the same, it has just been moved to other services. So I guess if you're having a max_execution_time error on extract, you should already have it before this PR.

> The DoctrineExtractor has two problems: First it has too much donation in it's extraction method, second it assumes that the twig template only use the entity and no other information.
For the Newsletter the member would need to be given as a parameter (named creator). (That's the only one I assume.)

I've added a `member` parameter for the template which should fix some of those issues.

What do you mean "_it has too much donation in its extraction method_"? I only see the user donations (in my case: none).

> The generated zip files doesn't contain the gallery items.

I don't see the problem anymore, I've uploaded some pictures on my gallery (member-2) and I can see them in the zip export.

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon As I said the execution timeout shouldn't have happened locally as the execution time was set to 0 which means no timeout. I assume the problem is with the configuration of symfony.

The hint to donations was meant regarding the variable names, which you fixed anyway without understanding the comment.

I merge now because I believe the gallery items problem was due to the wrong data directory.

**Pull request merged**
