### PR TITLE
RFR: Add GitHub Actions on PR

### PR DESCRIPTION
**Pull request by vincentchalamon**

### CODE REVIEW

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest Could you enable the GitHub Actions for this repository from here please: https://github.com/BeWelcome/rox/settings/actions

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon Not sure what to do here. 'Enable local and third party Actions for this repository ' is already checked.

**Comment by vincentchalamon** [comment]
:thinking: Maybe I must work on a branch in the repository to enable it...

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon Or maybe you need it to be enabled for your repository? 😄

**Comment by vincentchalamon** [comment]
Already enabled (by default). Maybe it's the yaml file which is invalid ^^ Looking for a validator

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest This PR is now RFR. I removed phpdox and phpmetrics analysis from CI as they're not installed in this project.

I recommend you to review the first commit only, as the second is just a fix for php-cs-fixer :wink:

**Comment by crumbking** [comment]
@vincentchalamon 
Not sure we need all these cs-fixer-fixes. Also as you say its hard to review in one commit. Could we do this separate? Maybe we fix rule by rule? Or we just use the symfony ruleset? Not sure as I'm not an expert.

**Comment by vincentchalamon** [comment]
@crumbking I've removed the _php-cs-fixer_ commit, it could be applied manually by @thisismeonmounteverest once merged.

**Comment by vincentchalamon** [comment]
Retry DeepCode

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon Not sure what you mean with I can manually execute the php-cs-fixer. If the check fails I would just deny merging the pull request to get it fixed, wouldn't I? :)

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest So you would prefer me to fix it in the PR, in contrary of what asked @crumbking ?

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon No, I don't want to run the php-cs-fixer as well. The fixer would fix things that should have been found by the other checks. So I assume they fail. 

If something fails a human should fix it.

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon Additionally everyone can run the fixer before committing anyway.

**Comment by vincentchalamon** [comment]
OK, so I keep my PR as it. Feel free to review/merge it :)

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon I should probably fix the failing tests first before merging :)

The DeepCode one seems to be rather brittle. Remove that one?

**Comment by vincentchalamon** [comment]
I could easily fix the PHP-CS-Fixer and PHP-Code-Sniffer checks by executing the php-cs-fixer script, but @crumbking didn't it in this PR.

I don't know about DeepCode, is it configured on the repository itself?

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon I removed DeepCode.

When I tried the php-cs-fixer script I got into a loop because the Code sniffer and the fixer had different ideas about what is correct. So the fixer would fix things and then the code sniffer would complain. Fixing things manually for the code sniffer made the fixer unhappy.

Maybe the new configuration works better? Which rules did you setup or did you keep the settings as is?

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest I've updated the configuration. PHP-CS-Fixer can be fixed by `php-cs-fixer` script, but PHP-Code-Sniffer requires a human intervention. I've already fixed both of them, would you like me to push the fixes?

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon Why would we waste your fixes? Please push.

**Comment by vincentchalamon** [comment]
Pushed.

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon Thanks. I add a few more exception (like the PaypalIPN class not being checked) later but merge now.

**Comment by vincentchalamon** [comment]
Thanks @thisismeonmounteverest 
I might work to fix PHP-MD in a later PR

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon I appreciate the offer but that is my mess :)
You probably want to add exciting features...

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon I'm struggling with some of my mess, maybe we could work on that together?

**Comment by vincentchalamon** [comment]
Yeah, sure, how can I help?

**Comment by thisismeonmounteverest** [comment]
There are lots of too many coupling of objects which I can't see how to fix.

**Comment by vincentchalamon** [comment]
Is there any chat we could discuss on, other than GitHub comments? It would be easier to help you I think

**Comment by thisismeonmounteverest** [comment]
We can use the chat on bewelcome.world (need to register though, is hosted by a member of BeWelcome). But not now as I'm at work :)

**Comment by vincentchalamon** [comment]
No problem. I'm just registered on bewelcome.world (username: vincent.chalamon), feel free to describe your problem there and I'll do my best to help you.
Not today neither as I'm at work, but tomorrow I should be free.

**Pull request merged**
