### PR TITLE
RFR: Allow geoname import on install

### PR DESCRIPTION
**Pull request by vincentchalamon**
- [x] Import geonames data on `make install-geonames`
- [x] Add documentation for install using Docker

### CODE REVIEW

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon While that will work that will create a really huge database and slow down the creation of the containers.
Do a make install-geonames instead?

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest I agree, but without the geonames the project will have a lot of 500 errors (cf. #138)

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon If you mean the problem on the profile page that isn't realated to missing geonames data but to wrong database seeding (and a problem in the old code I believe).

**Comment by vincentchalamon** [comment]
That's the problem I was talking about. And how could we fix it?

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon I'll fix that.
Having a way to add the full geonames to the db is usefull nevertheless I think.

**Comment by vincentchalamon** [comment]
Trying to load `import.sql` into the database, but I'm stuck with the following error:
> ERROR 1005 (HY000) at line 37: Can't create table `bewelcome`.`geonamescountries` (errno: 150 "Foreign key constraint is incorrectly formed")

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest Ready for review :-)

Importing geonames data is quite (very) long, but it fixes the issue on the profile:
bewelcome_profile

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon It certainly does :)

But the reason it shows up in the first place is a problem in the fixture. And there are a few entities missing/incorrect related to this.

**Pull request merged**
