### PR TITLE
Add docker-compose.yml and fix migrations to allow automatic initial setup.

### PR DESCRIPTION
**Pull request by omoustaouda**
While setting up my system I made a docker-compose.yml that can make life easier for the next contributors doing the same.

Setup commands are the ones listed here
https://github.com/BeWelcome/rox/blob/bootstrap4/INSTALL.md

Usage:
```~/rox$ docker-compose up --build --detach && docker-compose logs -f -t```

Output:
``` 
...
bewelcome_web | 2019-05-03T14:06:16.414419152Z Initial setup DONE
bewelcome_web | 2019-05-03T14:06:16.609464055Z 
bewelcome_web | 2019-05-03T14:06:16.609614266Z  [OK] Server listening on all interfaces, port 8000 -- see                      
bewelcome_web | 2019-05-03T14:06:16.609732645Z       http://172.26.0.3:8000                                                    
bewelcome_web | 2019-05-03T14:06:16.609747863Z 
bewelcome_web | 2019-05-03T14:06:16.609809546Z  // Quit the server with CONTROL-C.                                             
bewelcome_web | 2019-05-03T14:06:16.610015152Z 
bewelcome_web | 2019-05-03T14:06:16.635056988Z PHP 7.2.17 Development Server started at Fri May  3 14:06:16 2019
```

### CODE REVIEW

**Comment by omoustaouda** [comment]
I've updated the PR with af072b5aaef6bed8aeef6b8178102d3158ca9a7a
To use a custom Dockerfile, for having rebuilds running much faster, and to keep code clean and separated between server setup and app initialization.

**Comment by thisismeonmounteverest** [comment]
Could someone test this? Unfortunately I can't as I'm a Windows guy.

**Comment by guysoft** [comment]
Hey @thisismeonmounteverest Yes I can test it and would be happy to add docs on how to use it. Might even be able to host a test site.

When you run this now:

```
docker-compose build
docker-compose up -d
```
It seems to build and I can start the container, which gives this error in ``docker-compose logs``:

```
bewelcome_web | + composer install
bewelcome_web | Loading composer repositories with package information
bewelcome_web | Installing dependencies (including require-dev) from lock file
bewelcome_web | Your requirements could not be resolved to an installable set of packages.
bewelcome_web | 
bewelcome_web |   Problem 1
bewelcome_web |     - Installation request for lorenzo/pinky 1.0.5 -> satisfiable by lorenzo/pinky[1.0.5].
bewelcome_web |     - lorenzo/pinky 1.0.5 requires ext-xsl * -> the requested PHP extension xsl is missing from your system.
bewelcome_web |   Problem 2
bewelcome_web |     - Installation request for masterminds/html5 2.7.0 -> satisfiable by masterminds/html5[2.7.0].
bewelcome_web |     - masterminds/html5 2.7.0 requires ext-ctype * -> the requested PHP extension ctype is missing from your system.
bewelcome_web |   Problem 3
bewelcome_web |     - Installation request for sebastian/finder-facade 2.0.0 -> satisfiable by sebastian/finder-facade[2.0.0].
bewelcome_web |     - sebastian/finder-facade 2.0.0 requires ext-ctype * -> the requested PHP extension ctype is missing from your system.
bewelcome_web |   Problem 4
bewelcome_web |     - masterminds/html5 2.7.0 requires ext-ctype * -> the requested PHP extension ctype is missing from your system.
bewelcome_web |     - judev/php-htmltruncator 1.2.2 requires masterminds/html5 ^2.0 -> satisfiable by masterminds/html5[2.7.0].
bewelcome_web |     - Installation request for judev/php-htmltruncator 1.2.2 -> satisfiable by judev/php-htmltruncator[1.2.2].
bewelcome_web | 
bewelcome_web |   To enable extensions, verify that they are enabled in your .ini files:
bewelcome_web |     - /etc/php7/php.ini
bewelcome_web |     - /etc/php7/conf.d/00_dom.ini
bewelcome_web |     - /etc/php7/conf.d/00_fileinfo.ini
bewelcome_web |     - /etc/php7/conf.d/00_gd.ini
bewelcome_web |     - /etc/php7/conf.d/00_iconv.ini
bewelcome_web |     - /etc/php7/conf.d/00_json.ini
bewelcome_web |     - /etc/php7/conf.d/00_mbstring.ini
bewelcome_web |     - /etc/php7/conf.d/00_openssl.ini
bewelcome_web |     - /etc/php7/conf.d/00_pcntl.ini
bewelcome_web |     - /etc/php7/conf.d/00_pdo.ini
bewelcome_web |     - /etc/php7/conf.d/00_posix.ini
bewelcome_web |     - /etc/php7/conf.d/00_session.ini
bewelcome_web |     - /etc/php7/conf.d/00_simplexml.ini
bewelcome_web |     - /etc/php7/conf.d/00_tokenizer.ini
bewelcome_web |     - /etc/php7/conf.d/00_xml.ini
bewelcome_web |     - /etc/php7/conf.d/00_xmlwriter.ini
bewelcome_web |     - /etc/php7/conf.d/00_zip.ini
bewelcome_web |     - /etc/php7/conf.d/01_mysqlnd.ini
bewelcome_web |     - /etc/php7/conf.d/01_phar.ini
bewelcome_web |     - /etc/php7/conf.d/02_mysqli.ini
bewelcome_web |     - /etc/php7/conf.d/02_pdo_mysql.ini
bewelcome_web |     - /etc/php7/conf.d/xdebug.ini
bewelcome_web |   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by thisismeonmounteverest** [comment]
Looks like the php needs to get the xsl and ctype extensions updated during setup.

**Comment by guysoft** [comment]
Ok, I got the extensions (php7-xsl php7-ctype php7-curl) installed and it seems to be doing stuff.
Its complaning now that:
```
Fatal Error: composer.lock was created for PHP version 7.3.1 or higher but the current PHP version is 7.2.27.
```
Which makes sense because the Dockerfile has ``php7<7.3`` set. Fixing that rebuilding and expect a PR.

**Comment by guysoft** [comment]
Ok, its failing on composer insall now:
Any idea how to fix this? I am not experienced with PHP packages management to this level, only extensions.
```
bewelcome_web | + composer install
bewelcome_web | Loading composer repositories with package information
bewelcome_web | Installing dependencies (including require-dev) from lock file
bewelcome_web | Nothing to install or update
bewelcome_web | Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
bewelcome_web | Generating autoload files
bewelcome_web | ocramius/package-versions: Generating version class...
bewelcome_web | ocramius/package-versions: ...done generating version class
bewelcome_web | phpstan/extension-installer: Extensions installed
bewelcome_web | Executing script cache:clear [KO]
bewelcome_web |  [KO]
bewelcome_web | Script cache:clear returned with error code 1
bewelcome_web | !!  
bewelcome_web | !!   // Clearing the cache for the dev environment with debug                       
bewelcome_web | !!   // true                                                                        
bewelcome_web | !!  
bewelcome_web | !!  
bewelcome_web | !!  In AbstractMySQLDriver.php line 93:
bewelcome_web | !!                                                                                 
bewelcome_web | !!    An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir  
bewelcome_web | !!    ectory                                                                       
bewelcome_web | !!                                                                                 
bewelcome_web | !!  
bewelcome_web | !!  In PDOConnection.php line 31:
bewelcome_web | !!                                                      
bewelcome_web | !!    SQLSTATE[HY000] [2002] No such file or directory  
bewelcome_web | !!                                                      
bewelcome_web | !!  
bewelcome_web | !!  In PDOConnection.php line 27:
bewelcome_web | !!                                                      
bewelcome_web | !!    SQLSTATE[HY000] [2002] No such file or directory  
bewelcome_web | !!                                                      
bewelcome_web | !!  
bewelcome_web | !!  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
bewelcome_web | !!  
bewelcome_web | !!  
bewelcome_web | Script @auto-scripts was called via post-install-cmd
```

**Comment by thisismeonmounteverest** [comment]
The first composer install call needs --no-scripts I think. Otherwise we run into a deadlock with the translations coming from the database and the database not being there at that point.

**Comment by guysoft** [comment]
Ok, passed that, getting this now:
```
|   An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir  
bewelcome_web |   ectory                                                                       
```

Full log:
```
bewelcome_web | > node-sass@4.14.1 postinstall /var/Code/node_modules/node-sass
bewelcome_web | > node scripts/build.js
bewelcome_web | 
bewelcome_web | Binary found at /var/Code/node_modules/node-sass/vendor/linux_musl-x64-72/binding.node
bewelcome_web | Testing binary
bewelcome_web | Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
bewelcome_web | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
bewelcome_web | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
bewelcome_web | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
bewelcome_web | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
bewelcome_web | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
bewelcome_web | 
bewelcome_web | added 1664 packages from 625 contributors and audited 1673 packages in 60.023s
bewelcome_web | 
bewelcome_web | 37 packages are looking for funding
bewelcome_web |   run `npm fund` for details
bewelcome_web | 
bewelcome_web | found 1 high severity vulnerability
bewelcome_web |   run `npm audit fix` to fix them, or `npm audit` for details
+ php bin/console doctrine:schema:create --no-interaction
bewelcome_web | 
bewelcome_web |  !                                                                              
bewelcome_web |  ! [CAUTION] This operation should not be executed in a production environment! 
bewelcome_web |  !                                                                              
bewelcome_web | 
bewelcome_web |  Creating database schema...
bewelcome_web | 
bewelcome_web | 
bewelcome_web | In ToolsException.php line 34:
bewelcome_web |                                                                                
bewelcome_web |   Schema-Tool failed with Error 'An exception occurred in driver: SQLSTATE[HY  
bewelcome_web |   000] [2002] No such file or directory' while executing DDL: CREATE TABLE pa  
bewelcome_web |   rams (id INT AUTO_INCREMENT NOT NULL, updated DATETIME NOT NULL, IsRealProd  
bewelcome_web |   uctionDatabase VARCHAR(255) NOT NULL, recordonline INT NOT NULL, ToggleDona  
bewelcome_web |   teBar INT NOT NULL, neededperyear INT NOT NULL, campaignstartdate DATE NOT   
bewelcome_web |   NULL, MailToNotifyWhenNewMemberSignup TEXT NOT NULL, FeatureForumClosed VAR  
bewelcome_web |   CHAR(255) NOT NULL, FeatureAjaxChatClosed VARCHAR(255) NOT NULL, FeatureSig  
bewelcome_web |   nupClose VARCHAR(255) NOT NULL, FeatureSearchPageIsClosed VARCHAR(255) NOT   
bewelcome_web |   NULL, FeatureQuickSearchIsClosed VARCHAR(255) NOT NULL, RssFeedIsClosed VAR  
bewelcome_web |   CHAR(255) NOT NULL, AjaxChatSpecialAllowedList TEXT NOT NULL, AjaxChatDebuL  
bewelcome_web |   evel INT NOT NULL, ReloadRightsAndFlags VARCHAR(255) NOT NULL, logs_id_midn  
bewelcome_web |   ight INT NOT NULL, previous_logs_id_midnight INT NOT NULL, memcache VARCHAR  
bewelcome_web |   (255) NOT NULL, DayLightOffset INT NOT NULL, NbCommentsInLastComments INT N  
bewelcome_web |   OT NULL, IdCommentOfTheMoment INT NOT NULL, MailBotMode VARCHAR(255) NOT NU  
bewelcome_web |   LL, ToggleStatsForWordsUsage VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAUL  
bewelcome_web |   T CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_520_ci` ENGINE = InnoDB     
bewelcome_web |                                                                                
bewelcome_web | 
bewelcome_web | In AbstractMySQLDriver.php line 93:
bewelcome_web |                                                                                
bewelcome_web |   An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir  
bewelcome_web |   ectory                                                                       
bewelcome_web |                                                                                
bewelcome_web | 
bewelcome_web | In PDOConnection.php line 31:
bewelcome_web |                                                     
bewelcome_web |   SQLSTATE[HY000] [2002] No such file or directory  
bewelcome_web |                                                     
bewelcome_web | 
bewelcome_web | In PDOConnection.php line 27:
bewelcome_web |                                                     
bewelcome_web |   SQLSTATE[HY000] [2002] No such file or directory  
bewelcome_web |                                                     
bewelcome_web | 
bewelcome_web | doctrine:schema:create [--dump-sql] [--em [EM]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>
bewelcome_web | 
bewelcome_web exited with code 1

```

**Comment by thisismeonmounteverest** [comment]
Since the first try of this I added a symfony command to create the test database:

php bin/console test:database:create --drop --force

But the user bewelcome needs to be created upfront I believe as well.

**Pull request merged**
