### PR TITLE
Make docker work again #101

### PR DESCRIPTION
**Pull request by guysoft**
Work in progress, Related to #101 where the talks are still going

### CODE REVIEW

**Comment by thisismeonmounteverest** [comment]
The first composer install call needs --no-scripts I think. Otherwise we run into a deadlock with the translations coming from the database and the database not being there at that point.

Additionally the short open tags are no longer necessary.

**Comment by vincentchalamon** [comment]
Hi @guysoft @thisismeonmounteverest,

I just opened a PR to try to optimize the Docker configuration in this project, it might interest you: https://github.com/BeWelcome/rox/pull/138

Currently, this is a work in progress as I am building it locally. Feel free to check it on your machines and tell me what could be fixed on it :-)

Hope my PR could help to improve this project!

**Comment by guysoft** [comment]
Hey @vincentchalamon , 
Looks like a more overhaul work. I was trying to change the minimum for it to work. Your approach might be better because the container at the moment is indeed super basic an using official PHP might be a better move in the log run.
Would gladly help if you need anything with that.

**Comment by vincentchalamon** [comment]
> Would gladly help if you need anything with that.

Yes, with pleasure :-) I just arrived in this project, and don't know so much about its specificities. Could you test my branch locally, and ensure the project runs successfully? Otherwise, don't hesitate to tell me if there is anything wrong or to be optimized. My goal is to be able to run this project locally on every platforms using Docker: Linux, osX and Windows

**Comment by guysoft** [comment]
Also new here :)

**Comment by guysoft** [comment]
See #138

**Comment by guysoft** [comment]
Considering reopening since #138 is becoming pretty complicated, both me and another users can't reproduce a working environment with it. I really rather have an advance ``docker-compose.yml``, but working one is kinda more important.

**Comment by Jesus82** [comment]
Hi guys, if this is not the best place let me know where to ask. I'm trying to start docker with `docker-compose up --build --detach && docker-compose logs -f -t`
When doing that, I get this error:

```
bewelcome_web | 2020-05-26T19:43:58.364447827Z Your requirements could not be resolved to an installable set of packages.
bewelcome_web | 2020-05-26T19:43:58.364491286Z 
bewelcome_web | 2020-05-26T19:43:58.364502813Z   Problem 1
bewelcome_web | 2020-05-26T19:43:58.364511877Z     - masterminds/html5 2.7.0 requires ext-ctype * -> the requested PHP extension ctype is missing from your system.
bewelcome_web | 2020-05-26T19:43:58.364524238Z     - masterminds/html5 2.7.0 requires ext-ctype * -> the requested PHP extension ctype is missing from your system.
bewelcome_web | 2020-05-26T19:43:58.364552833Z     - Installation request for masterminds/html5 2.7.0 -> satisfiable by masterminds/html5[2.7.0].
bewelcome_web | 2020-05-26T19:43:58.364561464Z 
bewelcome_web | 2020-05-26T19:43:58.364569058Z   To enable extensions, verify that they are enabled in your .ini files:
bewelcome_web | 2020-05-26T19:43:58.364575694Z     - /etc/php7/php.ini
bewelcome_web | 2020-05-26T19:43:58.364581935Z     - /etc/php7/conf.d/00_dom.ini
bewelcome_web | 2020-05-26T19:43:58.364588255Z     - /etc/php7/conf.d/00_fileinfo.ini
bewelcome_web | 2020-05-26T19:43:58.364595225Z     - /etc/php7/conf.d/00_gd.ini
bewelcome_web | 2020-05-26T19:43:58.364602047Z     - /etc/php7/conf.d/00_iconv.ini
bewelcome_web | 2020-05-26T19:43:58.364608743Z     - /etc/php7/conf.d/00_json.ini
bewelcome_web | 2020-05-26T19:43:58.364615737Z     - /etc/php7/conf.d/00_mbstring.ini
bewelcome_web | 2020-05-26T19:43:58.364622793Z     - /etc/php7/conf.d/00_openssl.ini
bewelcome_web | 2020-05-26T19:43:58.364629328Z     - /etc/php7/conf.d/00_pcntl.ini
bewelcome_web | 2020-05-26T19:43:58.364662347Z     - /etc/php7/conf.d/00_pdo.ini
bewelcome_web | 2020-05-26T19:43:58.364669573Z     - /etc/php7/conf.d/00_posix.ini
bewelcome_web | 2020-05-26T19:43:58.364676421Z     - /etc/php7/conf.d/00_session.ini
bewelcome_web | 2020-05-26T19:43:58.364683664Z     - /etc/php7/conf.d/00_simplexml.ini
bewelcome_web | 2020-05-26T19:43:58.364690427Z     - /etc/php7/conf.d/00_tokenizer.ini
bewelcome_web | 2020-05-26T19:43:58.364697701Z     - /etc/php7/conf.d/00_xml.ini
bewelcome_web | 2020-05-26T19:43:58.364704546Z     - /etc/php7/conf.d/00_xmlwriter.ini
bewelcome_web | 2020-05-26T19:43:58.364711526Z     - /etc/php7/conf.d/00_zip.ini
bewelcome_web | 2020-05-26T19:43:58.364718862Z     - /etc/php7/conf.d/01_mysqlnd.ini
bewelcome_web | 2020-05-26T19:43:58.364726067Z     - /etc/php7/conf.d/01_phar.ini
bewelcome_web | 2020-05-26T19:43:58.364733126Z     - /etc/php7/conf.d/02_mysqli.ini
bewelcome_web | 2020-05-26T19:43:58.364739880Z     - /etc/php7/conf.d/02_pdo_mysql.ini
bewelcome_web | 2020-05-26T19:43:58.364746853Z     - /etc/php7/conf.d/xdebug.ini
bewelcome_web | 2020-05-26T19:43:58.364753882Z   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```
Any guess what should I do? I have php 7.4, 7.3 and 7.2 installed and running Ubuntu 20.04

**Comment by thisismeonmounteverest** [comment]
@Jesus82 : Please check #138. That's more likely to fulfill your needs.

**Pull request closed without merging**
