### PR TITLE
Implement Member API

### PR DESCRIPTION
**Pull request by vincentchalamon**
Please read the Behat scenarios for more information about usage.

- [x] Install & configure API Platform
- [x] Add lexik/jwt-authentication-bundle for API authentication
- [x] Install & configure Behat tests
- [x] Enable read-only ApiResource on Member entity
- [x] Expose Member public properties
- [x] Expose owner only Member properties
- [x] Expose Member properties if not hidden
- [x] Add Member filters
- [x] Add security on Member API
- [x] Use composer:1 on Dockerfile
- [x] Install python for yarn packages (required by sass dependencies)

## Actions required for production

- Create [lexik/jwt-authentication-bundle](https://packagist.org/packages/lexik/jwt-authentication-bundle) certificates:
```bash
openssl genpkey -out config/jwt/private.pem -pass stdin -aes256 -algorithm rsa -pkeyopt rsa_keygen_bits:4096
openssl pkey -in config/jwt/private.pem -passin stdin -out config/jwt/public.pem -pubout
```
- Declare `JWT_PASSPHRASE` environment variable with the passphrase used on previous commands
- Declare `JWT_SECRET_KEY` and `JWT_PUBLIC_KEY` environment variables with the path of the previous files

### CODE REVIEW

**Comment by vincentchalamon** [comment]
@thisismeonmounteverest FYI, the Doctrine schema is invalid, about AlternateLocation and Location association.

**Comment by thisismeonmounteverest** [comment]
As all CI validation use PHP 7.4 shouldn't docker also be configured to do so?

**Comment by vincentchalamon** [comment]
Is the production server running on PHP 7.4.12 ?

**Comment by thisismeonmounteverest** [comment]
@vincentchalamon Yes, it is.

**Comment by vincentchalamon** [comment]
Functional and unit tests are passing, so as all other tests, except for the infection tests. I suggest they could be fixed in another PR later, so we could merge the current PR to continue development.

**Pull request merged**
